services:
  - type: web
    name: mern-backend
    env: node
    branch: main
    plan: starter
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars: []

  - type: static
    name: mern-frontend
    branch: main
    plan: starter
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
